ShoppingCart/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ShoppingCart.DataAccessLayer;
using ShoppingCart.Models;
using ShoppingCart.Services;

namespace ShoppingCart.Controllers
{
    public class CartController : Controller
    {
        private readonly AccountService _accountService;
        private readonly AppDbContext db;

        public CartController(AppDbContext db, AccountService accountService)
        {
            _accountService = accountService;
            this.db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IEnumerable<ProductJsonModel> Index([FromBody] ProductRequestModel[] cartItems)
        {
            List<ProductJsonModel> result = new List<ProductJsonModel>();
            List<Product> productListing = new List<Product>();
            // list of product ids in localStorage.
            List<string> cartProductIds = new List<string>();
            if (cartItems != null)
            {
                foreach (var item in cartItems)
                {
                    cartProductIds.Add(item.Id);
                }
                var cartProducts = db.Products.Where(p => cartProductIds.Contains(p.ProductId)).ToList();

                foreach (var product in cartProducts)
                {
                    result.Add(new ProductJsonModel()
                    {
                        ProductDescription = product.ProductDescription,
                        ProductId = product.ProductId,
                        ProductImg = product.ProductImg,
                        ProductName = product.ProductName,
                        ProductPrice = product.ProductPrice
                    });
                }
            }
            return result;
        }

        [HttpPost]
        public bool Checkout([FromBody] ProductRequestModel[] checkoutCart)
        {
    
            if (_accountService.Authenticate() && checkoutCart.Any())
            {
                var userSession = db.Sessions.FirstOrDefault(x => x.SessionId == HttpContext.Session.GetString("SessionId"));
                if (userSession != null)
                {
                    var userId = userSession.UserId;
                    List<string> checkoutCartIds = new List<string>();
                    foreach (var p in checkoutCart)
                    {
                        checkoutCartIds.Add(p.Id);
                    }
                    string OrderId = Guid.NewGuid().ToString();
                    for (int i = 0; i < checkoutCart.Length; i++)
                    {
                        var product = db.Products.FirstOrDefault(p => p.ProductId == checkoutCart[i].Id);
                        if (product != null)
                        {
                            double productPrice = product.ProductPrice;

                            OrderDetail orderDetail = new OrderDetail
                            {
                                OrderId = OrderId,
                                ProductId = checkoutCart[i].Id,
                                Quantity = checkoutCart[i].Count,
                                ProductPrice = productPrice
                            };
                            db.OrderDetails.Add(orderDetail);

                            for (int j = 0; j < checkoutCart[i].Count; j++)
                            {
                                ActivationCode activationCode = new ActivationCode
                                {
                                    Code = Guid.NewGuid().ToString(),
                                    ProductId = checkoutCart[i].Id,
                                    OrderId = orderDetail.OrderId
                                };
                                db.ActivationCodes.Add(activationCode);
                            }
                        }
                    }
                    db.Orders.Add(new Order
                    {
                        OrderId = OrderId,
                        UserId = userId,
                        Timestamp = DateTime.Now
                    });
                    db.SaveChanges();
                    return true;
                }
            }
            return false;
        }
    }
}

ShoppingCart/Controllers/OrdersController.cs
using Castle.DynamicProxy.Generators.Emitters.SimpleAST;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using ShoppingCart.DataAccessLayer;
using ShoppingCart.Models;
using ShoppingCart.Services;

namespace ShoppingCart.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDbContext db;
        private readonly AccountService _accountService;

        public OrdersController(AppDbContext db, AccountService accountService)
        {
            _accountService = accountService;
            this.db = db;
        }

        public IActionResult Index()
        {
            if (!_accountService.Authenticate())
            {
                string returnUrl = HttpContext.Request.Path.Value.ToString();
                return RedirectToAction("Index", "Account", new { returnUrl });
            }

            int? userId = HttpContext.Session.GetInt32("UserId");

            var orders = db.Orders.Where(x => x.UserId == userId).OrderByDescending(x => x.Timestamp).ToList();
            List<PurchaseViewModel> purchases = new List<PurchaseViewModel>();
            foreach (Order order in orders)
            {
                var orderDetails = db.OrderDetails.Include(x => x.Product).OrderBy(x => x.Product.ProductName).Where(od => od.OrderId == order.OrderId && od.ProductId == od.Product.ProductId).ToList();
                foreach (var detail in orderDetails)
                {
                    PurchaseViewModel purchase = new PurchaseViewModel();
                    purchase.OrderId = detail.OrderId;
                    purchase.Date = order.Timestamp;
                    purchase.ProductId = detail.ProductId;
                    purchase.PurchasePrice = detail.ProductPrice;
                    purchase.Quantity = detail.Quantity;
                    purchase.Rating = detail.Rating;
                    purchase.ProductName = detail.Product.ProductName;
                    purchase.ProductDescription = detail.Product.ProductDescription;
                    purchase.ProductImg = detail.Product.ProductImg;
                    purchase.ActivationCodes = db.ActivationCodes.Where(ac => ac.ProductId == detail.ProductId && ac.OrderId == detail.OrderId).ToList();
                    purchases.Add(purchase);
                }
            }
            return View(purchases);
        }

        [HttpPost]
        public IActionResult UpdateRating([FromBody] OrderDetail updatedOrderDetails)
        {
            OrderDetail orderdetail = db.OrderDetails.FirstOrDefault(x => x.OrderId == updatedOrderDetails.OrderId && x.ProductId == updatedOrderDetails.ProductId);
            if (orderdetail != null)
            {
                orderdetail.Rating = updatedOrderDetails.Rating;
                db.SaveChanges();
                Debug.WriteLine("successful");
            }
            return Json(new { updatedOrderDetails });
        }
    }
}

ShoppingCart/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Shopping_Cart_Web_Application.styles.css" asp-append-version="true" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <style>
        .checked {
            color: orange;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Shopping Cart App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-text">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            //Check if user has a valid session ID. If yes, display logout button.
                            if (HttpContextAccessor.HttpContext.Session.GetString("SessionId") != null)
                            {
                                string name = "Hello, " + HttpContextAccessor.HttpContext.Session.GetString("Name");
                                <li class="navbar-text">
                                    <b>@name</b>
                                    &nbsp
                                </li>
                                <li class="vr"></li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            // If user doesn't have a valid session ID, display login button on all pages except for login page itself.
                            else
                            {
                                if (HttpContextAccessor.HttpContext.Request.Path != "/Account")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Login</a>
                                    </li>
                                }
                            }
                            <li class="vr"></li>
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            //For cart page, gallery page link is renamed as "Continue Shopping".
                            if (HttpContextAccessor.HttpContext.Request.Path == "/Cart")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Continue Shopping</a>
                                </li>
                            }
                            //For all other pages, gallery page link is named as "Gallery".

                            else if (HttpContextAccessor.HttpContext.Request.Path == "/Account" || HttpContextAccessor.HttpContext.Request.Path == "/Orders")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Gallery</a>
                                </li>
                            }
                            // Display Orders page "My Purchases" on navigation bar if valid sessionID is found.
                            if (HttpContextAccessor.HttpContext.Session.GetString("SessionId") != null && HttpContextAccessor.HttpContext.Request.Path != "/Orders")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">My Purchases</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div class="navbar-text">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="btn btn-outline-dark" id="lnkShoppingCart" asp-area="" asp-controller="Cart" asp-action="Index">
                                <i class="bi-cart-fill me-1"></i>
                                Cart
                                <span id="cartTotal" class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 h-100">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-2" style="position:absolute; width: 100%; bottom: 0;">
        <div class="container">
            &copy; 2022 - ShoppingCart App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>